development:
  adapter: postgresql
  encoding: unicode
  database: Pomodoro_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: Pomodoro_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: Pomodoro_production
  pool: 5
